In [2]:
import spacy
from spacy.lang.en.stop_words import STOP_WORDS
st= STOP_WORDS

In [4]:
len(st)

326

In [5]:
nlp= spacy.load('en_core_web_sm')
doc= nlp('We just opened our wings, the flying part is coming soon')

In [8]:
for token in doc:
    if not token.is_stop:
        print(token)

opened
wings
,
flying
coming
soon

In [12]:
def process(text):
    doc= nlp(text)
    
    stop_word_removal= [token.text for token in doc if not token.is_stop]
    return " ".join(stop_word_removal)

In [13]:
process("Musk wants time to prepare for a trial over his")

'Musk wants time prepare trial'

In [16]:
process("Heloo! hope are you i am fine hope you are also very good and fit andf enjoying your life")

'Heloo ! hope fine hope good fit andf enjoying life'

In [17]:
import pandas as pd

In [20]:
df = pd.read_json("combined.json", lines =True)

In [21]:
df.head(5)

,id,title,contents,date,topics,components
0,None,Convicted Bomb Plotter Sentenced to 30 Years,"PORTLAND, Oregon. – Mohamed Osman Mohamud, 23,...",2014-10-01T00:00:00-04:00,[],[National Security Division (NSD)]
1,12-919,$1 Million in Restitution Payments Announced t...,WASHINGTON – North Carolina’s Waccamaw River...,2012-07-25T00:00:00-04:00,[],[Environment and Natural Resources Division]
2,11-1002,$1 Million Settlement Reached for Natural Reso...,BOSTON– A $1-million settlement has been...,2011-08-03T00:00:00-04:00,[],[Environment and Natural Resources Division]
3,10-015,10 Las Vegas Men Indicted \r\nfor Falsifying V...,WASHINGTON—A federal grand jury in Las Vegas...,2010-01-08T00:00:00-05:00,[],[Environment and Natural Resources Division]
4,18-898,$100 Million Settlement Will Speed Cleanup Wor...,"The U.S. Department of Justice, the U.S. Envir...",2018-07-09T00:00:00-04:00,[Environment],[Environment and Natural Resources Division]

In [22]:
df.shape

(13087, 6)

In [24]:
df= df[df['topics'].str.len() != 0]

In [25]:
df.head(5)

,id,title,contents,date,topics,components
4,18-898,$100 Million Settlement Will Speed Cleanup Wor...,"The U.S. Department of Justice, the U.S. Envir...",2018-07-09T00:00:00-04:00,[Environment],[Environment and Natural Resources Division]
7,14-1412,14 Indicted in Connection with New England Com...,A 131-count criminal indictment was unsealed t...,2014-12-17T00:00:00-05:00,[Consumer Protection],[Civil Division]
19,17-1419,2017 Southeast Regional Animal Cruelty Prosecu...,The United States Attorney’s Office for the Mi...,2017-12-14T00:00:00-05:00,[Environment],"[Environment and Natural Resources Division, U..."
22,15-1562,21st Century Oncology to Pay $19.75 Million to...,"21st Century Oncology LLC, has agreed to pay $...",2015-12-18T00:00:00-05:00,"[False Claims Act, Health Care Fraud]",[Civil Division]
23,17-1404,21st Century Oncology to Pay $26 Million to Se...,21st Century Oncology Inc. and certain of its ...,2017-12-12T00:00:00-05:00,"[Health Care Fraud, False Claims Act]","[Civil Division, USAO - Florida, Middle]"

In [33]:
df.shape

(4688, 6)

In [37]:
df= df.head(1000)

In [38]:
df.shape

(1000, 6)

In [40]:
df["Clear_Content"]= df.contents.apply(process)

In [41]:
len(df.Clear_Content.iloc[2])

3347